- name: copy file
  copy: src=iperf-2.0.6.tar.gz dest=/tmp/iperf-2.0.6.tar.gz mode=0777

- name: tar file
  shell: cd /tmp && tar xvf iperf-2.0.6.tar.gz && rm -rf iperf-2.0.6.tar.gz

- name: run install
  shell: "cd /tmp/iperf && ./install.sh"
  ignore_errors: yes
