- name: copy file
  copy: src=iperf-2.0.5.tar.gz dest=/tmp/iperf-2.0.5.tar.gz mode=0777

- name: tar file
  shell: cd /tmp && tar xvf iperf-2.0.5.tar.gz && rm -rf iperf-2.0.5.tar.gz

- name: run install on aarch64
  copy: src=iperf dest=/usr/bin/ mode=0755
  when: ansible_architecture == "aarch64"
  ignore_errors: yes

- name: run install on x86 
  shell: "cd /tmp/iperf-2.0.5 && ./install.sh"
  when: ansible_architecture != "aarch64"
  ignore_errors: yes








